modLoader="javafml"
loaderVersion="${loader_version}"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheIllusiveC4/Bedspreads/issues"
logoFile="bedspreads_icon.png"
logoBlur=false
[[mods]]
modId="bedspreads"
version="${version}"
displayName="Bedspreads"
displayURL="https://github.com/TheIllusiveC4/Bedspreads"
authors="C4"
description='''
Allows players to add banner patterns to their beds!
'''
[[dependencies.bedspreads]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.bedspreads]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"
